$schema:            http://json-schema.org/draft-04/schema#
title:              Config
description: |-
  The global configuration settings used by taskcluster-worker, not particular
  to any engine or plugin.
type:               object
properties:
  pollingInterval:
    title: "PollingInterval"
    description: "The amount of time to wait between task polling iterations"
    type: "integer"
  credentials:
    title:          Credentials
    description: |-
      The set of credentials that should be used by the worker when
      authenticating against taskcluster endpoints.
    type:           object
    properties:
      clientId:
        title:          ClientId
        description: |-
          The Client ID for the client. Not very helpful, am I?
        type:           string
        pattern:        ^[A-Za-z0-9@/:._-]+$
      accessToken:
        title:          AccessToken
        description: |-
          The security-sensitive access token for the client. Do not share or expose!
        pattern:        ^[a-zA-Z0-9_-]{22,66}$
        type:           string
      certificate:
        title:          Certificate
        description: |-
          The certificate for the client, if using temporary credentials and/or using authorized scopes.
        type:           string
    required:
      - clientId, accessToken, certificate
  provisionerId:
    title:          ProvisionerId
    description: |-
      The provisioner (if any) that is responsible for spawning instances of this worker. Typically `aws-provisioner-v1`.
    type:           string
  workerGroup:
    title:          WorkerGroup
    description: |-
      A logical group for this worker to belong to, such as an AWS region.
    type:           string
  workerType:
    title:          WorkerType
    description: |-
      Type of worker pool the worker belongs to.
    type:           string
  workerId:
    title:          WorkerId
    description: |-
      A unique name that can be used to identify which worker instance this is (such as AWS instance id).
    type:           string
  capacity:
    title:          Capacity
    description: |-
      The number of tasks that this worker supports running in parallel.
    type:           integer
  queueService:
    title:          QueueService
    description: |-
      Configuration relating to the polling of the TaskCluster Queue.
    type:           object
    properties:
      expirationOffset:
        title:          ExpirationOffset
        description: |-
          The number of seconds prior to the task claim expiry that tasks should be reclaimed.
        type:           integer
    required:
      - expirationOffset
additionalProperties: false
required:
  - credentials, provisionerId, workerGroup, workerId, capacity, queueService
